# Inspired by: https://github.com/docascode/docfx-seed/blob/master/appveyor.yml
image: Visual Studio 2017
environment:
  # TODO configure your own project by changing values of environment variables
  git_repo: NormandErwan/AU
  git_user_email: normand.erwan@protonmail.com
  git_user_name: Erwan Normand
  auth_token:
    secure: 6ofAZV1tmD6f2ubY3R3QNjkxAg+zyniEYixAia6FjzKNhcQeY+mYOFAx2vWi8hdp
install:
  - choco install docfx -y
build_script:
  - cp README.md Documentation/index.md
  - docfx Documentation/docfx.json
after_build:
  # Clone repo's gh-pages branch (see: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages)
  - ps: |
        git clone https://$($env:oauth_token)@github.com/$env:git_repo -b gh-pages gh-pages
        cd gh-pages
  # Remove old docs (necessary to have clean new docs)
  # But keep the Unity's xref maps (specific to DocFxForUnity, you can remove it for you own project)
  - ps: |
        Get-ChildItem -exclude Unity | rm -r
  # Add, commit and push new docs
  - ps: |
        cp -r ..\_site\* .
        git add --all | out-null

        git config --global user.email $env:git_user_email
        git config --global user.name $env:git_user_name
        git commit -m "Documentation update"

        git push origin gh-pages