image: Visual Studio 2017
environment:
  # TODO configure your own project by changing values of environment variables
  git_repo: NormandErwan/AU
  git_user_email: normand.erwan@protonmail.com
  git_user_name: NormandErwan
  # See: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
  auth_token:
    secure: 6ofAZV1tmD6f2ubY3R3QNjkxAg+zyniEYixAia6FjzKNhcQeY+mYOFAx2vWi8hdp
install:
  - choco install docfx -y
build_script:
  - cp README.md Documentation/index.md
  - docfx Documentation/docfx.json
after_build:
  # Clone repo's gh-pages branch where docs are
  - ps: |
        git clone https://github.com/$env:git_repo -b gh-pages gh-pages --quiet
        cd gh-pages
  # Replace old docs (necessary to have clean new docs)
  # But keep the Unity's xref maps folder (specific to DocFxForUnity, you can keep only the `rm -r` on you own project)
  - ps: |
        Get-ChildItem -exclude Unity | rm -r
        cp -r ..\_site\* .
  # Add, commit and push new docs (see for details: https://www.appveyor.com/docs/how-to/git-push/)
  - ps: |
        git config --global core.safecrlf false
        git add --all | out-null

        git config --global user.email $env:git_user_email
        git config --global user.name $env:git_user_name
        git commit -m "Documentation update" --quiet

        git config --global credential.helper store
        Add-Content "$HOME\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
        git push origin gh-pages --quiet